name: calcium
channels:
  - defaults
dependencies:
  - pandas
  - plotly=5.10.0
  - jupyter-dash
  - more-itertools
  - ipywidgets[version='>=7.6']
  - jupyterlab[version='>=3']
  - ipykernel
  - jupyter
  - nodejs
  - xarray
  - natsort
  - scipy
  - tqdm
  - scikit-learn
  - typing
  - zarr
  - matplotlib
  - networkx
  - python-kaleido
  - statsmodels
  - pyyaml
  - dask
  - ffmpeg
  - holoviews
  - pymannkendall
  - pingouin
  - pyarrow
  - black
  - ca-certificates
  - certifi
  - openssl
  - pynwb
  - datetimerange
  - mne=1.1.0
  - yasa
  - poppler
  - umap-learn
  - netcdf4
  - h5netcdf
